### ISSUE TITLE
i can't into app 

### ISSUE THREAD

**Issue by muaviya** [zagahr/Conferences.digital#10]
<img width="1292" alt="Снимок экрана 2019-03-21 в 15 54 56" src="https://user-images.githubusercontent.com/4594192/54753331-d4266b80-4bf1-11e9-857c-107accc51ca6.png">

**Comment by zagahr** [comment]
Are you based in Russia?

**Comment by muaviya** [comment]
yes


>Пятница, 29 марта 2019, 21:49 +03:00 от Timon Blask <notifications@github.com>:
>
>Are you based in Russia?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Исмаил Хасбулатов
ismaisan@mail.ru

**Comment by zagahr** [comment]
Sorry about that. 

Please watch #5 for progress on that topic.
