### ISSUE TITLE
Maybe also add meetups?

### ISSUE THREAD

**Issue by MarcoMiltenburg** [zagahr/Conferences.digital#16]
Although they are not conferences, maybe you can also add meetups?  I produce the videos for [CocoaHeadsNL](https://www.youtube.com/stichtingcocoaheadsnl) and [SwiftUG Amsterdam](https://swift.amsterdam/talks.html) and I think they are on par with many of the videos from the conferences.

**Comment by zagahr** [comment]
Yes sure. Thank you for your suggestion. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
