### ISSUE TITLE
Add recent conferences

### ISSUE THREAD

**Issue by ghv** [zagahr/Conferences.digital#18]
Seems the ConferencesCore.framework controls this. Is there a way to add these?

* [iOS Con](https://skillsmatter.com/conferences/10823-ioscon-2019-the-conference-for-ios-and-swift-developers?#skillscasts)
* [CodeMobile 2019](https://www.youtube.com/playlist?list=PLmEZjI7vcqES-hEaDBXVFtyJ_5mUa0umr)
* [try! Swift Tokyo 2019](https://www.youtube.com/playlist?list=PLCl5NM4qD3u_L8dJrWYbLB8FcUaoAHDFt)
* [App Builders Switzerland 2019](https://www.youtube.com/playlist?list=PLLcE3DL3f5Bx0IAHAw6hsdZ3z_samz2iX)

**Comment by alekseypotapov-dev** [comment]
Also 

- [NSSpain](https://vimeo.com/nsspain)

**Comment by zagahr** [comment]
Thanks for the links. I'm currently really busy and can't tell when I able to add them.

If someone wants to help out, please send me JSON in the format below!

```json
{
	"Try Swift 2019": {
		"talks": [{
			"title": "The Philosopher's String",
			"source": "youtube",
			"videoId": "lMhGnTFA9CI",
			"details": "Swift’s String type aims to strike an optimal balance between correctness, performance, and ease ofuse. This talk will explore the philosophy behind String and how we as a community can drive ease ofuse evenfurther to make programming with String a true joy.",
			"speaker": {
				"name": "Michael Ilseman",
				"twitter": "https://twitter.com/Ilseman",
				"github": "",
				"bio": "Michael works at Apple on Swift’s Standard Library team."
			}
		}]
	},
	"CodeMobile 2019": {
		"talks": []
	}
}
```

**Comment by jstart** [comment]
@zagahr Working on it! https://gist.github.com/jstart/24b02b140708f00bf67bf38f51ad04eb
