### ISSUE TITLE
Conferences sources

### ISSUE THREAD

**Issue by arguiot** [zagahr/Conferences.digital#2]
It would be great to have the possibility to add our own sources or just have a catalog of different sources (WWDC for example).

It would make the app more open and add support for other languages (JavaScript for example).

**Comment by zagahr** [comment]
I will try to update the catalog in the future.

**Comment by ghost** [comment]
Adding WWDC will be really good. And I wanted to watch dot 2019 but I think there are more videos on their website?

**Comment by pdiazmon** [comment]
Even not only more sources. Could be great to have the possibility to add (and create) more tags to the videos.
