### ISSUE TITLE
Unable to process the data returned by the server

### ISSUE THREAD

**Issue by FloLecoeuche** [zagahr/Conferences.digital#20]
Hello,
i've downloaded the app and since the first launch i see a black screen with "Unable to process the data returned by the server".

![Screenshot 2020-01-09 at 13 24 29](https://user-images.githubusercontent.com/2616127/72067678-a2e36d00-32e3-11ea-9e69-a734b55d7193.png)

**Comment by zagahr** [comment]
Hi,
which version of the app are you using?

**Comment by FloLecoeuche** [comment]
The problem occurs on the version 20 with the 21 it's fixed.
Thank you
