### ISSUE TITLE
Replace YoutubeWebView with AVPlayer

### ISSUE THREAD

**Issue by zagahr** [zagahr/Conferences.digital#3]
Hello everyone,

I would love to replace the current YoutubeWebView with a native AVPlayer solution, but in order to achieve this, I will need access to the original/raw video files. As you might know, most videos are hosted on YouTube. Therefore I'm am not able/allowed to access the original video file. (Due to YouTube's Legal Agreements)

However, most videos are uploaded under creative commons licenses, which means — correct me if I’m wrong — that redistribution is allowed when the original author is credited.

So my question is: 
Would it be legal to re-upload the original video file to a separate file server and then refer to the original author/source?

**Comment by arguiot** [comment]
Great idea 👍! I wouldn't recommend re-uploading videos, but what you can do is take the video URL from the youtube player and use AVPlayer from that. Many apps do that (so I believe it's legal).

In order to do that, you can use https://github.com/mojilala/YoutubeSourceParserKit or do something like IINA: download the video before reading it using `youtube-dl`

**Comment by zagahr** [comment]
Thank you for your feedback!

Unfortunately frameworks like YouTubeSourceParserKit are against YouTub‘s ToC.

„Warning: This repo is for educational purposes. This is not approved by the ToC of YouTube. Use at own risk.“

**Comment by kandelvijaya** [comment]
This is interesting in both how youtube works and what we want to do. Just to be clear: are there any significant drawbacks for using YoutubeWebView for now?

**Comment by zagahr** [comment]
No, not for now. But it would be nice to use fullscreen or PiP mode in the future.

**Comment by rolandkakonyi** [comment]
Hi @zagahr! What about adding a fullscreen button and grow the WKWebView to take the whole window and trigger it become full screen?
This is just an idea from top of my head. It could be a lite solution to support full screen.

Note: I have 0 mac development experience, so I'm not sure if this can work, but would be nice.

**Comment by paulofierro** [comment]
WKWebView's PIP support appears to be currently iOS only. Fullscreen could be possible via a custom button that handles this transition manually or uses the [Javascript Full Screen API](https://caniuse.com/#search=fullscreen)

Unfortunately following Youtube's ToS leads to a worse user experience, which is probably why this particular section is often ignored 😕 

I would love to use the native player instead (and enable the PIP and fullscreen buttons) 😅
