### ISSUE TITLE
Create Website

### ISSUE THREAD

**Issue by zagahr** [zagahr/Conferences.digital#4]
Would be nice to have to have a very simple website.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by koalahl** [comment]
it's better. We can see conferences everywhere.

**Comment by zagahr** [comment]
I just want a very simple promotion website and not an actual website where you can watch conferences videoes. If you want to watch conference videos on a website checkout: http://www.swifttube.co
