### ISSUE TITLE
Server's IP address is blocked in Russia

### ISSUE THREAD

**Issue by ivanglushko** [zagahr/Conferences.digital#5]
Can't connect to the server. 
Once I used VPN and set my country to UK everything went great.
P.S I'm located in Russia.

And thank you for the great app!

![Screenshot 2019-03-11 at 11 14 43](https://user-images.githubusercontent.com/36343782/54112465-e123ad80-43ee-11e9-8ac4-c1e444b30ae5.png)

**Comment by zagahr** [comment]
Oh, that's interesting. I'll look into it.

**Comment by makartsev** [comment]
@zagahr what server do you use? I think that your server ip is blocked in Russia. You can check it here: https://eais.rkn.gov.ru/en/

**Comment by zagahr** [comment]
My server is hosted on DigitalOcean and yes you are right - the server ip address is blocked in Russia. The only solution would be to change the provider or are there any other solutions?

**Comment by makartsev** [comment]
It's sad. I'm using DigitalOcean too. But I selected Amsterdam 3 region and it works in Russia well. What region did you select?
