### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by tomaskraina** [zagahr/Conferences.digital#6]
First, thanks for developing this app and open-sourcing it! 🎉 

It would be awesome to port it to iOS so I could use it on my iPad, for example.

I haven't yet looked through the whole codebase, do you think there's something that would make it difficult to do so?

**Comment by zagahr** [comment]
Thank you for your feedback! 👍 

I think it should be very easy to port it to iOS! I already have it on my roadmap but contributions are welcome!

**Comment by tomaskraina** [comment]
Perfect! Where do you reckon I should start then? :) If you have any thoughts about how to approach this, I would like to hear it.

**Comment by zagahr** [comment]
Sorry for the late response.

We are already working on the iOS app - contributors are always welcome!

You can find the repository here: https://github.com/zagahr/Conferences-for-iOS

If you consider contributing make sure to join the slack channel: https://join.slack.com/t/conferencesdigital/shared_invite/enQtNTc3MjEyNzE0NTYxLTU2NTgxOTI3YjBlN2JkZTA2ODAxMTQ0OWJlMDhmMjZmZWMzNTA1OTM3YjQ3YzRkZjZhZGEzNzdhN2M2ZjAxNDI
