### ISSUE TITLE
The app shows as damaged after downloading

### ISSUE THREAD

**Issue by sbrighiu** [zagahr/Conferences.digital#9]
![Screen Shot 2019-03-19 at 11 08 18](https://user-images.githubusercontent.com/6714874/54593476-54ed3800-4a37-11e9-9d00-c2f56e036df9.png)

Am I missing something?

**Comment by zagahr** [comment]
https://github.com/zagahr/Conferences.digital#installation

**Comment by sbrighiu** [comment]
It does not appear in Settings > Security & Privacy

**Comment by sbrighiu** [comment]
![image](https://user-images.githubusercontent.com/6714874/54593769-e3fa5000-4a37-11e9-8051-6b7b0fa8935c.png)

**Comment by zagahr** [comment]
Try to right-click the app and select "Open". Lets me know if this works.

**Comment by sbrighiu** [comment]
I did, it usually works the first time.
I got it, 10th try ... macOSX finally showed the prompt ... it just takes a bit ...
For those having the same issue, it always helps to close System Preferences completely and try again ;)

**Comment by vermont42** [comment]
Thanks, @sbrighiu. Worked the tenth time for me also. @zagahr Would you mind if I add a note about this to the readme?

**Comment by zagahr** [comment]
No of course! Will add it to the readme.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JMatharu** [comment]
This solution was not working for me, although I was able to fix it with `xattr`

eg

`xattr -cr /path/to/application.app`

The -c flag removes all attributes, whereas -r applies recursively for the entire targeted .app directory contents.

**Comment by mrWONDERFULguy** [comment]
not working...with right click  open
